version: '2.1'
services:
  rabbitmq-teste:
    image: rabbitmq:3.6-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    container_name: rabbitmq-wallet-teste
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=b2b

  mongodb-teste:
    image: mongo:3.6.1
    container_name: mongodb-wallet-teste
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - MONGO_DATA:/data/db
    ports:
      - 27017:27017
    command: mongod

volumes:
  MONGO_DATA:
  SQL_DATA: